# Generated by Django 5.0.4 on 2024-05-29 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="タイトル")),
            ],
        ),
        migrations.CreateModel(
            name="PhotoPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="タイトル")),
                ("comment", models.TextField(verbose_name="コメント")),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos", verbose_name="イメージ1"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos", verbose_name="イメージ2"
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="投稿日時"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="photo.category",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザ",
                    ),
                ),
            ],
        ),
    ]
